name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run the app for tests
      - name: Run the app
        run: npm start &

      # 5️⃣ Wait for app to start
      - name: Wait for server
        run: sleep 5

      # 6️⃣ Test endpoint(s)
      - name: Test /test endpoint
        run: curl -f http://localhost:5000/test

      # 7️⃣ Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 8️⃣ Build Docker image with commit SHA tag
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:latest

      # 9️⃣ Push both tags to DockerHub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:latest

  deploy:
    name: Deploy to AWS EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Stopping old container..."
            docker stop hello-docker || true
            docker rm hello-docker || true
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ github.sha }}
            echo "Starting new container..."
            docker run -d -p 5000:5000 --name hello-docker ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ github.sha }}
            echo "✅ Deployment completed successfully!"
